BEGIN TRANSACTION;
CREATE TABLE "pokemon" (
	`_id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT UNIQUE,
	`type1`	TEXT,
	`type2`	TEXT
);
INSERT INTO `pokemon` VALUES (1,'Bulbasaur','Grass','Poison');
INSERT INTO `pokemon` VALUES (2,'Ivysaur','Grass','Poison');
INSERT INTO `pokemon` VALUES (3,'Venusaur','Grass','Poison');
INSERT INTO `pokemon` VALUES (4,'Charmander','Fire','None');
INSERT INTO `pokemon` VALUES (5,'Charmeleon','Fire','None');
INSERT INTO `pokemon` VALUES (6,'Charizard','Fire','Flying');
INSERT INTO `pokemon` VALUES (7,'Squirtle','Water','None');
INSERT INTO `pokemon` VALUES (8,'Wartortle','Water','None');
INSERT INTO `pokemon` VALUES (9,'Blastoise','Water','None');
INSERT INTO `pokemon` VALUES (10,'Caterpie','Bug','None');
INSERT INTO `pokemon` VALUES (11,'Metapod','Bug','None');
INSERT INTO `pokemon` VALUES (12,'Butterfree','Bug','Flying');
INSERT INTO `pokemon` VALUES (13,'Weedle','Bug','Poison');
INSERT INTO `pokemon` VALUES (14,'Kakuna','Bug','Poison');
INSERT INTO `pokemon` VALUES (15,'Beedrill','Bug','Poison');
INSERT INTO `pokemon` VALUES (16,'Pidgey','Normal','Flying');
INSERT INTO `pokemon` VALUES (17,'Pidgeotto','Normal','Flying');
INSERT INTO `pokemon` VALUES (18,'Pidgeot','Normal','Flying');
INSERT INTO `pokemon` VALUES (19,'Rattata','Normal','None');
INSERT INTO `pokemon` VALUES (20,'Raticate','Normal','None');
INSERT INTO `pokemon` VALUES (21,'Spearow','Normal','Flying');
INSERT INTO `pokemon` VALUES (22,'Fearow','Normal','Flying');
INSERT INTO `pokemon` VALUES (23,'Ekans','Poison','None');
INSERT INTO `pokemon` VALUES (24,'Arbok','Poison','None');
INSERT INTO `pokemon` VALUES (25,'Pikachu','Electric','None');
INSERT INTO `pokemon` VALUES (26,'Raichu','Electric','None');
INSERT INTO `pokemon` VALUES (147,'Dratini','Dragon','None');
INSERT INTO `pokemon` VALUES (148,'Dragonair','Dragon','None');
INSERT INTO `pokemon` VALUES (149,'Dragonite','Dragon','Flying');
INSERT INTO `pokemon` VALUES (150,'Mewtwo','Psychic','None');
INSERT INTO `pokemon` VALUES (151,'Mew','Psychic','None');
INSERT INTO `pokemon` VALUES (152,'Chikorita','Grass','None');
INSERT INTO `pokemon` VALUES (153,'Bayleef','Grass','None');
INSERT INTO `pokemon` VALUES (154,'Meganium','Grass','None');
INSERT INTO `pokemon` VALUES (155,'Cyndaquil','Fire','None');
INSERT INTO `pokemon` VALUES (156,'Quilava','Fire','None');
INSERT INTO `pokemon` VALUES (157,'Typhlosion','Fire','None');
INSERT INTO `pokemon` VALUES (249,'Lugia','Psychic','Flying');
INSERT INTO `pokemon` VALUES (250,'Ho-oh','Fire','Flying');
INSERT INTO `pokemon` VALUES (251,'Celebi','Psychic','Grass');
INSERT INTO `pokemon` VALUES (252,'Treecko','Grass','None');
INSERT INTO `pokemon` VALUES (253,'Grovyle','Grass','None');
INSERT INTO `pokemon` VALUES (254,'Sceptile','Grass','None');
INSERT INTO `pokemon` VALUES (448,'Lucario','Fighting','Steel');
INSERT INTO `pokemon` VALUES (468,'Togekiss','Fairy','Flying');
INSERT INTO `pokemon` VALUES (647,'Keldeo','Water','Fighting');
INSERT INTO `pokemon` VALUES (648,'Meloetta','Normal','Psychic');
INSERT INTO `pokemon` VALUES (649,'Genesect','Bug','Steel');
INSERT INTO `pokemon` VALUES (650,'Chespin','Grass','None');
INSERT INTO `pokemon` VALUES (651,'Quilladin','Grass','None');
INSERT INTO `pokemon` VALUES (652,'Chesnaught','Grass','Fighting');
INSERT INTO `pokemon` VALUES (653,'Fennekin','Fire','None');
INSERT INTO `pokemon` VALUES (654,'Braixen','Fire','None');
INSERT INTO `pokemon` VALUES (655,'Delphox','Fire','Psychic');
INSERT INTO `pokemon` VALUES (714,'Noibat','Flying','Dragon');
INSERT INTO `pokemon` VALUES (715,'Noivern','Flying','Dragon');
INSERT INTO `pokemon` VALUES (716,'Xerneas','Fairy','None');
INSERT INTO `pokemon` VALUES (717,'Yveltal','Dark','Flying');
INSERT INTO `pokemon` VALUES (718,'Zygarde','Dragon','Ground');
INSERT INTO `pokemon` VALUES (719,'Diancie','Rock','Fairy');
INSERT INTO `pokemon` VALUES (720,'Hoopa','Psychic','Ghost');
INSERT INTO `pokemon` VALUES (721,'Volcanion','Fire','Water');
INSERT INTO `pokemon` VALUES (802,'Alolan Rattata','Dark','Normal');
INSERT INTO `pokemon` VALUES (803,'Alolan Raticate','Dark','Normal');
INSERT INTO `pokemon` VALUES (804,'Alolan Raichu','Electric','Psychic');
COMMIT;